// Explications détaillées de chaque commande (utilisées par : help <commande>)
// [description, utilisation, exemple]
module.exports = {
  menu: ["Affiche le menu illustré : infos du bot (propriétaire, mode, version) et toutes les commandes avec leur description.", "menu", "menu"],
  allmenu: ["Affiche la liste compacte de toutes les commandes, classées par catégorie (noms seulement).", "allmenu", "allmenu"],
  help: ["Sans nom : guide général du bot. Avec un nom de commande : explique en détail ce que fait cette commande.", "help  ou  help <commande>", "help humm"],
  ping: ["Mesure la vitesse de réponse du bot (délai entre ton message et son arrivée sur le serveur).", "ping", "ping"],
  alive: ["Montre que le bot est actif : temps de fonctionnement, RAM utilisée, nombre de sessions connectées, mode et version.", "alive", "alive"],
  public: ["Passe le bot en mode public : tout le monde peut utiliser les commandes.", "public", "public"],
  owner: ["Envoie les fiches de contact des créateurs (IB-SACKO & SALGA) et du propriétaire (SALGADO), avec les boutons « Message » et « Ajouter un contact ».", "owner", "owner"],
  settings: ["Affiche les paramètres : mode du bot, antidelete. Dans un groupe, montre aussi l'état de chaque protection et si le bot est admin.", "settings", "settings"],
  mode: ["Choisit qui peut utiliser le bot. En mode private, seul le propriétaire est écouté ; en public, tout le monde.", "mode public  ou  mode private", "mode private"],
  kick: ["Expulse un membre du groupe. Cible : mention, réponse à son message, ou numéro écrit.", "kick @membre  (ou réponds à son message)", "kick @224999888777"],
  kickall: ["Expulse tous les membres du groupe. Le bot annonce d'abord la purge par 3 messages mystérieux (le premier notifie tout le monde), attend quelques secondes, puis retire les membres par lots de 5 et affiche le bilan. Les admins, le bot et toi-même êtes épargnés. Aucune confirmation : à utiliser avec prudence.", "kickall", "kickall"],
  mute: ["Ferme le groupe : seuls les admins peuvent écrire.", "mute", "mute"],
  unmute: ["Rouvre le groupe : tout le monde peut de nouveau écrire.", "unmute", "unmute"],
  tagall: ["Mentionne tous les membres du groupe dans un message stylé : nom du groupe, qui a lancé, nombre de membres et d'admins, heure, ton message. Les admins sont listés en premier. Dans un gros groupe, la liste est découpée en parties de 50. « tagall admins » ne mentionne que les admins.", "tagall  ·  tagall <message>  ·  tagall admins <message>", "tagall Réunion à 20h"],
  tag: ["Mentionne une ou plusieurs personnes avec un texte. Fonctionne aussi en répondant au message de quelqu'un.", "tag @membre <message>", "tag @224999888777 viens voir !"],
  warn: ["Donne un avertissement à un membre. À 3 avertissements, il est expulsé automatiquement (le compteur est partagé avec les protections).", "warn @membre  (ou réponds à son message)", "warn @224999888777"],
  welcome: ["Active ou désactive le message de bienvenue quand quelqu'un rejoint le groupe (avec sa photo de profil si elle existe).", "welcome on  ou  welcome off", "welcome on"],
  goodbye: ["Active ou désactive le message d'au revoir quand quelqu'un quitte le groupe.", "goodbye on  ou  goodbye off", "goodbye on"],
  setmenuimage: ["Change l'image affichée avec le menu (pour ton bot uniquement). Réponds à une image, ou donne un lien. « reset » remet l'image d'origine.", "setmenuimage <lien>  ou réponds à une image  ou  setmenuimage reset", "setmenuimage https://site.com/image.jpg"],
  pair: ["Génère un code de connexion pour lier un autre numéro WhatsApp au bot. Le code est envoyé seul dans un 2e message (facile à copier). Le bot te prévient dès que le numéro est relié, ou si le code expire. Options : « pair status <numéro> » (état d'un numéro) et « pair list » (sessions connectées, numéros masqués) — réservées aux propriétaires du système. Limite : 1 code toutes les 20 secondes.", "pair <numéro avec indicatif>  ·  pair status <numéro>  ·  pair list", "pair 224621963059"],
  antispam: ["Détecte le flood : 6 messages en 6 secondes ou moins → messages supprimés + avertissement. 3 avertissements = expulsion. Admins exemptés.", "antispam on  ou  antispam off", "antispam on"],
  antilink: ["Supprime les liens envoyés par les non-admins (http, www, chat.whatsapp.com, wa.me, t.me) et avertit. 3 avertissements = expulsion.", "antilink on  ou  antilink off", "antilink on"],
  antimarabout: ["Supprime les messages d'arnaque type marabout / voyance / retour d'affection / multiplication d'argent, avertit puis expulse au 3e.", "antimarabout on  ou  antimarabout off", "antimarabout on"],
  antidelete: ["Quand quelqu'un supprime un message (groupe ou privé), le bot t'envoie en privé un rapport avec le message supprimé (texte, image, vidéo, audio, sticker, document). Les médias « vue unique » sont aussi récupérés. Réservé au propriétaire.", "antidelete on  ou  antidelete off", "antidelete on"],
  antibot: ["Détecte les messages envoyés par d'autres bots (à partir de leur identifiant de message), les supprime et expulse le bot.", "antibot on  ou  antibot off", "antibot on"],
  antistatus: ["Supprime les statuts qui mentionnent le groupe. 1er : avertissement 1/3, 2e : dernier avertissement, 3e : expulsion. Admins exemptés.", "antistatus on  ou  antistatus off", "antistatus on"],
  antisticker: ["Supprime les stickers envoyés par les non-admins et avertit. 3 avertissements = expulsion.", "antisticker on  ou  antisticker off", "antisticker on"],
  antipurge: ["Protège contre les purges : si un admin retire 4 membres ou plus en 60 secondes, il est rétrogradé et les membres retirés sont réajoutés.", "antipurge on  ou  antipurge off", "antipurge on"],
  image: ["Cherche des images sur le web (Pinterest) et en envoie jusqu'à 5.", "image <recherche>", "image chat mignon"],
  sticker: ["Transforme une image ou une vidéo (12 s max) en sticker avec le pack CENTRAL-HEX. Réponds au média, ou envoie-le avec « sticker » en légende.", "sticker  (en répondant à une image/vidéo)", "sticker"],
  stickersearch: ["Cherche des GIF animés et les envoie directement sous forme de stickers (jusqu'à 4).", "stickersearch <mot>", "stickersearch chat"],
  toimg: ["Convertit un sticker en image (sticker fixe) ou en vidéo/GIF (sticker animé).", "toimg  (en répondant à un sticker)", "toimg"],
  waouh: ["Récupère un média « vue unique » (photo, vidéo ou audio) : tu réponds au message, le bot te l'envoie en privé et confirme dans la discussion.", "waouh  (en répondant à un média vue unique)", "waouh"],
  humm: ["Comme waouh, mais en version discrète : le bot ne répond rien et ne met aucune réaction dans la discussion. Il t'envoie simplement le média vue unique dans ta discussion privée. Il ne s'exécute que si tu réponds à un vrai média vue unique ; sinon, il ne se passe rien. Le média n'est jamais renvoyé dans le groupe.", "humm  (en répondant à un média vue unique)", "humm"],
  lyrics: ["Trouve les paroles d'une chanson à partir de son titre (et de l'artiste, pour être plus précis).", "lyrics <titre> <artiste>", "lyrics Blinding Lights The Weeknd"],
  ss: ["Prend une capture d'écran d'un site web et l'envoie en image.", "ss <lien>", "ss https://wikipedia.org"],
  save: ["Sauvegarde un média (image, vidéo, audio, sticker, document) dans ta discussion privée. Réponds au média concerné.", "save  (en répondant à un média)", "save"],
  google: ["Fait une recherche web et affiche les 6 premiers résultats avec titre, extrait et lien.", "google <recherche>", "google recette du thieboudienne"],
  play: ["Cherche une application sur le Play Store et donne jusqu'à 5 liens.", "play <nom de l'application>", "play whatsapp"],
  video: ["Cherche une vidéo YouTube (ou prend un lien YouTube) et l'envoie en MP4. Durée maximale : 15 minutes.", "video <titre ou lien YouTube>", "video Burna Boy Last Last"],
  song: ["Cherche une musique sur YouTube (ou prend un lien) et l'envoie en audio, avec la miniature et les infos. Durée maximale : 20 minutes.", "song <titre ou lien YouTube>", "song Davido Unavailable"],
  mediafire: ["Télécharge un fichier depuis un lien MediaFire et l'envoie en document (jusqu'à 90 Mo ; au-delà, tu reçois le lien direct).", "mediafire <lien MediaFire>", "mediafire https://www.mediafire.com/file/..."],
  facebook: ["Télécharge une vidéo Facebook à partir de son lien (vidéos publiques).", "facebook <lien>", "facebook https://facebook.com/watch/..."],
  instagram: ["Télécharge les photos et vidéos (reels, posts) d'un lien Instagram public. Jusqu'à 5 médias.", "instagram <lien>", "instagram https://instagram.com/reel/..."],
  tiktok: ["Télécharge une vidéo TikTok à partir de son lien, en HD et sans filigrane quand c'est disponible.", "tiktok <lien>", "tiktok https://vm.tiktok.com/..."],
  getpp: ["Récupère la photo de profil de la personne mentionnée ou citée, ou la tienne si tu ne précises personne. Ne marche pas si la photo est privée.", "getpp  ou  getpp @membre", "getpp @224999888777"],
  goodnight: ["Envoie un joli message de bonne nuit, avec une mention si tu désignes quelqu'un.", "goodnight  ou  goodnight @membre", "goodnight @224999888777"],
  wcg: ["Affiche le classement des 10 membres les plus actifs du groupe, selon les messages comptés depuis que le bot est dans le groupe.", "wcg", "wcg"],
  quizz: ["Pose une question de culture générale à 4 choix. Réponds par A, B, C ou D dans les 45 secondes ; le bot dit si c'est juste.", "quizz", "quizz"],
  anime: ["Envoie une image d'anime. Types possibles : waifu, neko, shinobu, megumin, hug, pat, kiss, cuddle, smile, wave, happy, wink, dance, cry, blush, highfive.", "anime  ou  anime <type>", "anime neko"],
  profile: ["Affiche la fiche d'un membre : nom, numéro, statut, photo, et dans un groupe son rôle (admin/membre) et son nombre de messages. Sans précision, c'est ton profil.", "profile  ou  profile @membre", "profile @224999888777"],
  couple: ["Choisit deux membres du groupe au hasard et annonce leur compatibilité en pourcentage (pour rire).", "couple", "couple"],
  poll: ["Crée un sondage WhatsApp. Sépare la question et les choix avec « | ». Minimum 2 choix, maximum 12.", "poll Question | choix 1 | choix 2 | choix 3", "poll Pizza ou burger ? | Pizza | Burger"],
  emojimix: ["Mélange deux emojis en un seul sticker. Écris-les séparés par « + ».", "emojimix <emoji1>+<emoji2>", "emojimix 😎+🥰"]
};
